print('hello world')
print('the quick brown fox', 'jumps over', 'the lazy dog')
print('100 + 200 = ', 100 + 200)
name = input('Please enter your name:')
print('hello', name)
print('I\'m ok.')
print('I\'m learning\nPython')
